/**
 * `mf spec` generator (M12.5): the LLM-facing language handbook, built
 * from the same registries the engine runs on — choice lists, verb
 * defaults, stages, error codes. The committed `docs/SPEC.md` is
 * drift-checked in CI against this generator; regenerate with
 * `pnpm mf spec --out docs/SPEC.md` after any language change.
 */

import { EASING_NAMES, GRADE_KINDS, TRANSITION_KINDS } from '@motionforge/core';

import { EFFECT_DEFAULT_SECONDS } from './compile.js';
import { MF_CODES } from './errors.js';
import {
  CARD_STYLE_CHOICES,
  CAST_PALETTE_SLOTS,
  COSTUME_CHOICES,
  EXPRESSION_CHOICES,
  FONT_CHOICES,
  GESTURE_CHOICES,
  HELD_CHOICES,
  MUSIC_MOOD_CHOICES,
  MUSTACHE_CHOICES,
  REACTION_CHOICES,
  SHOT_CHOICES,
  VERB_NAMES,
} from './schema.js';
import { STAGE_PRESET_NAMES } from './stage.js';

export interface SpecVerbInfo {
  readonly summary: string;
  readonly defaultSeconds: number;
  readonly defaultSfx?: string;
}

export interface SpecExtras {
  /** Motion-registry verbs: name → summary + defaults (CLI supplies). */
  readonly verbs?: Readonly<Record<string, SpecVerbInfo>>;
  readonly stylePresets?: readonly string[];
  readonly sfxNames?: readonly string[];
  readonly mapSources?: readonly string[];
}

/** Summaries for verbs the language owns (compiled to clips, not registry
 * effects). Every VERB_NAMES entry must have a summary here or in the
 * registry — the drift test enforces it. */
export const LANG_VERB_SUMMARIES: Readonly<Record<string, string>> = {
  move: 'Tween an instance to a position over `duration` seconds.',
  rotate: 'Tween an instance to an angle (degrees, counter-clockwise).',
  scale: 'Tween an instance to a uniform scale factor.',
  'bounce-to': 'The default character move: hop-slide with a body bob; hops derive from distance.',
  caption: 'Screen-fixed shaped text (multi-script) at a world position.',
  card: 'Timed overlay panel — see the Cards chapter for the styles.',
  cutaway: 'A framed shape snippet inside a paper frame.',
  camera:
    'Camera moves: `to`/`zoom` glides, `cut: true`, `whip: true` pans, `zoom-punch:` at a target, `shake:`, and damped `track:` (see Cinematography).',
  shot: 'Framing presets: wide, medium, close-up, two-shot, region (see Cinematography).',
  'zoom-to': "Frame a map region's bounding box (margin + easing).",
  map: 'Map verbs on a placed map: `recolor:` sweeps, `highlight:`, `morph:` (territory change).',
  arrow: 'A curved growing offensive arrow between regions or points.',
  march: 'Unit icons (infantry/cavalry/ship/plane) marching along a path with dust.',
  battle: 'Clash stars + smoke burst at a point or region.',
  'plant-flag': 'Plant a waving flag at a point or region centroid.',
  label: "A region nameplate with a halo, popping in at the region's centroid.",
  enter: 'Walk on stage from a wing (`from: left|right`); the actor starts offstage.',
  exit: 'Walk off stage into a wing (`to: left|right`).',
  chase: 'Two actors ping-pong across the stage, pursuer trailing by a beat.',
  react: 'A face reaction (jaw-drop, eye-bulge, …) with companion particles.',
  gesture: 'A rig-pose gesture layered on the idle (point, wave, salute, …).',
  posture: 'A held body state (sit, kneel, lie-down, stand) that persists.',
  keyframes: 'Escape hatch: hand-authored frames on one property of an instance/part/bone.',
  sfx: 'An explicit sound cue by name (see the Audio chapter).',
};

const list = (items: readonly string[]): string => items.map((i) => `\`${i}\``).join(', ');

const verbTable = (extras: SpecExtras): string => {
  const rows = VERB_NAMES.map((name) => {
    const registry = extras.verbs?.[name];
    const summary = registry?.summary ?? LANG_VERB_SUMMARIES[name] ?? '';
    const seconds = registry?.defaultSeconds ?? EFFECT_DEFAULT_SECONDS[name];
    const sfx = registry?.defaultSfx;
    const notes = [seconds !== undefined ? `${seconds}s` : '—', sfx ? `sfx \`${sfx}\`` : '']
      .filter(Boolean)
      .join(', ');
    return `| \`${name}\` | ${summary.replaceAll('\n', ' ')} | ${notes} |`;
  });
  return ['| Verb | What it does | Default |', '|---|---|---|', ...rows].join('\n');
};

/** Generate the complete spec document. Deterministic for fixed inputs. */
export function generateSpec(extras: SpecExtras = {}): string {
  return `# MotionForge screenplay spec (MFS v2)

> Generated by \`mf spec\` (M12.5) — do not edit by hand. Regenerate with
> \`pnpm mf spec --out docs/SPEC.md\`. CI fails if this file drifts from
> the registries.

One \`.mfs.yaml\` file describes one finished, narrated film. Authors
write **seconds** and **degrees**; the world is y-up, origin at screen
center, 10 world units tall. Everything renders deterministically — same
file, same bytes.

## Document skeleton

\`\`\`yaml
motionforge: 2
meta:
  title: My Film
  resolution: 1280x720
  fps: 30
  seed: 7                      # drives all wobble/shake randomness
  style: explainer-paper       # ${(extras.stylePresets ?? []).join(' | ')}
  subtitles: { font: noto-sans }   # optional auto-subtitles (M11.2)
voices:
  narrator: { engine: mock, voice: warm }   # engines: qwen | recorded | mock
cast:                          # named characters (see Cast)
objects:                       # part-tree props; use: pulls in libraries
maps:                          # basemaps + groups + custom regions (see Maps)
scenes:
  - id: intro
    stage: { preset: throne-room }     # ${STAGE_PRESET_NAMES.join(' | ')}
    music: { mood: jaunty, gain: 90 }  # moods: ${MUSIC_MOOD_CHOICES.join(' | ')}
    transition: { kind: iris }         # ${TRANSITION_KINDS.join(' | ')}
    grade: dusk                        # ${GRADE_KINDS.join(' | ')}
    place:
      - { ref: king, as: king, at: [-2, -2.6], facing: right }
    narration:
      - voice: narrator
        text: Words the narrator speaks.
        subtitle: Optional translated subtitle text.
        sync:
          - { on: 'narrator speaks', do: { sfx: ding } }
    lines:
      - { after: 'a phrase', speaker: king, say: Short squeak., react: deadpan }
    actions:
      - { at: 1.5, move: { target: king, to: [2, -2.6], duration: 1 } }
\`\`\`

Scene duration comes from the narration audio (plus pauses) or an
explicit \`duration:\`. Every scene needs one of the two.

## Verbs

Timed \`actions:\` entries carry \`at:\` seconds; \`sync:\` entries fire
on a narration phrase (\`on:\`, optional \`offset:\`, \`nth:\` for
repeats). Both share the same verb payloads:

${verbTable(extras)}

## Narration & sync

- Anchors quote a phrase from the segment's \`text:\`; the frozen
  alignment (\`mf voice sync\`) maps it to word timestamps.
- \`lines:\` are character one-liners anchored \`after:\` a phrase; the
  narration ducks under them, the speaker flap-mouths with a speech
  bubble.
- \`meta.subtitles\` auto-generates timed subtitle chunks from narration
  text + alignment; per-segment \`subtitle:\` overrides carry
  translations (Bengali under English VO, etc.).

## Cast

Templates: \`potato-biped\`, \`horse\`, \`dog\` (horse/dog carry a seat —
ride them with \`place.on\`). Palette slots: ${list(CAST_PALETTE_SLOTS)}.

- Expressions: ${list(EXPRESSION_CHOICES)}
- Costume pieces: ${list(COSTUME_CHOICES)}
- Mustaches: ${list(MUSTACHE_CHOICES)}
- Held items: ${list(HELD_CHOICES)}
- Reactions (\`react:\`): ${list(REACTION_CHOICES)}
- Gestures (\`gesture:\`): ${list(GESTURE_CHOICES)}

## Maps

Sources: ${list(extras.mapSources ?? [])}. A map is placed like any
object; regions are parts named by kebab-case country id. \`groups:\`
name alliances; \`regions:\` add hand-drawn lon/lat blobs (optionally
replacing base regions). Map verbs: \`map.recolor\` (staggered sweep),
\`map.highlight\`, \`map.morph\`, \`arrow\`, \`march\`, \`battle\`,
\`plant-flag\`, \`label\`, and \`zoom-to\` for camera framing.

## Cards

Styles: ${list(CARD_STYLE_CHOICES)}. Entrances: \`pop\`, \`slam\`.
\`title\` takes an optional \`subtext:\`; \`lower-third\` is the
broadcast name strap (\`text:\` name, \`subtext:\` role). List cards pop
items one by one. Cards read at ~15 chars/s — the validator lints
timing.

## Cinematography

- \`camera:\` — \`to:\`/\`zoom:\` glides (\`easing:\`), \`cut: true\`,
  \`whip: true\` (whip-pan + speed dip), \`zoom-punch: <cast|point>\`
  (\`punch:\` strength), \`shake: <intensity>\`, \`track: <instance>\`
  (damped-spring follow; \`stiffness:\`, \`offset:\`).
- \`shot:\` — presets ${list(SHOT_CHOICES)} (\`of:\` subjects,
  \`rect:\` for region, \`cut: true\` to snap).
- Scene \`transition:\` — ${list(TRANSITION_KINDS)}; scene \`grade:\` —
  ${list(GRADE_KINDS)}.

## Audio

Music moods: ${list(MUSIC_MOOD_CHOICES)} (procedural beds; \`gain:\`
percent). SFX cues: ${list(extras.sfxNames ?? [])} — explicit via
\`sfx:\`, and many verbs bring their own (see the verb table). Narration
levels toward a target loudness; music ducks under voice; lines duck the
narration.

## Easings & fonts

Easings: ${list(EASING_NAMES)}. Fonts: ${list(FONT_CHOICES)} — mixed
scripts fall back automatically per script run.

## Error codes

\`mf check\` findings carry these stable codes (full pages under
\`docs/errors/\`):

${Object.entries(MF_CODES)
  .map(([code, title]) => `- **${code}** — ${title}`)
  .join('\n')}
`;
}
